
sync_args: "--process-groups --users mapped"
root_config: "user-sync-config.yml"
fail_on_error: false
allowed_errors:
  #- can't open file

assertions: |-
  managing groups for user key: federatedid,callsaul4@usersynctest.com, added: {'test group 1'} removed: set()
  managing groups for user key: federatedid,callsaul@usersynctest.com, added:
  managing groups for user key: federatedid,callsaul3@usersynctest.com, added: {'test group 1'} removed: set()
  managing groups for user key: federatedid,callsaul5@usersynctest.com, added: {'test group 1'} removed: set()
  managing groups for user key: federatedid,callsaul2@usersynctest.com, added: {'test group 1'} removed: set()
  creating user with user key: federatedid,callsaul1@usersynctest.com
  creating user with user key: federatedid,callsaul6@usersynctest.com
  creating user with user key: federatedid,callsaul7@usersynctest.com
  creating user with user key: federatedid,callsaul8@usersynctest.com
  creating user with user key: federatedid,callsaul9@usersynctest.com

